import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import base64, io, os

df = pd.read_csv('outputs/clean_data.csv')
os.makedirs('outputs', exist_ok=True)

def fig_to_base64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode('utf-8')

fig1, ax1 = plt.subplots(figsize=(8,4))
df['age'].hist(bins=20, color='steelblue', edgecolor='white', ax=ax1)
ax1.set_title('Age Distribution of Patients', fontsize=14)
ax1.set_xlabel('Age'); ax1.set_ylabel('Count')
img1 = fig_to_base64(fig1); plt.close()

fig2, ax2 = plt.subplots(figsize=(8,4))
df['chol'].hist(bins=20, color='tomato', edgecolor='white', ax=ax2)
ax2.set_title('Cholesterol Distribution', fontsize=14)
ax2.set_xlabel('Cholesterol (mg/dL)'); ax2.set_ylabel('Count')
img2 = fig_to_base64(fig2); plt.close()

fig3, ax3 = plt.subplots(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt='.2f', cmap='coolwarm', ax=ax3)
ax3.set_title('Feature Correlation Heatmap', fontsize=14)
img3 = fig_to_base64(fig3); plt.close()

fig4, ax4 = plt.subplots(figsize=(6,4))
df['condition'].value_counts().plot(kind='bar', color=['steelblue','tomato'], ax=ax4)
ax4.set_title('Risk Distribution', fontsize=14)
ax4.set_xticklabels(['Low Risk (0)','High Risk (1)'], rotation=0)
img4 = fig_to_base64(fig4); plt.close()

high_risk = df[df['condition']==1]
low_risk  = df[df['condition']==0]

html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SmartClinic AI - EDA Report</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 1100px; margin: 0 auto; padding: 30px; background: #f8fafc; color: #1e293b; }
  h1 { color: #1a6b8a; border-bottom: 3px solid #1a6b8a; padding-bottom: 10px; }
  h2 { color: #2e6da4; margin-top: 40px; }
  .stats-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 16px; margin: 24px 0; }
  .stat-card { background: white; border-radius: 8px; padding: 20px; text-align: center; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  .stat-value { font-size: 2rem; font-weight: bold; color: #1a6b8a; }
  .stat-label { font-size: 0.9rem; color: #64748b; margin-top: 4px; }
  .chart-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin: 24px 0; }
  .chart-box { background: white; border-radius: 8px; padding: 16px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  .chart-box img { width: 100%; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #1a6b8a; color: white; padding: 12px; text-align: left; }
  td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
  .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>SmartClinic AI - Exploratory Data Analysis Report</h1>
<p>Dataset: Heart Disease Cleveland UCI | Generated by Agent 2</p>
<h2>Dataset Overview</h2>
<div class="stats-grid">
  <div class="stat-card"><div class="stat-value">TOTAL</div><div class="stat-label">Total Patients</div></div>
  <div class="stat-card"><div class="stat-value">COLS</div><div class="stat-label">Features</div></div>
  <div class="stat-card"><div class="stat-value">HIGH</div><div class="stat-label">High Risk</div></div>
  <div class="stat-card"><div class="stat-value">LOW</div><div class="stat-label">Low Risk</div></div>
</div>
<h2>Visualizations</h2>
<div class="chart-grid">
  <div class="chart-box"><img src="data:image/png;base64,IMG1" alt="Age"></div>
  <div class="chart-box"><img src="data:image/png;base64,IMG2" alt="Cholesterol"></div>
  <div class="chart-box"><img src="data:image/png;base64,IMG3" alt="Heatmap"></div>
  <div class="chart-box"><img src="data:image/png;base64,IMG4" alt="Risk"></div>
</div>
<h2>Key Findings</h2>
<ul>
  <li>Dataset: TOTAL patients, COLS features.</li>
  <li>Risk: HIGH high-risk vs LOW low-risk.</li>
  <li>Mean age: AGE years. Mean cholesterol: CHOL mg/dL.</li>
  <li>Chest pain type and max heart rate are strongly correlated with condition.</li>
</ul>
<div class="footer">SmartClinic AI | Hebrew University of Jerusalem | 2026</div>
</body></html>"""

html = html.replace("TOTAL", str(len(df)))
html = html.replace("COLS",  str(len(df.columns)))
html = html.replace("HIGH",  str(len(high_risk)))
html = html.replace("LOW",   str(len(low_risk)))
html = html.replace("AGE",   f"{df['age'].mean():.1f}")
html = html.replace("CHOL",  f"{df['chol'].mean():.1f}")
html = html.replace("IMG1",  img1)
html = html.replace("IMG2",  img2)
html = html.replace("IMG3",  img3)
html = html.replace("IMG4",  img4)

with open('outputs/eda_report.html', 'w') as f:
    f.write(html)
print('eda_report.html saved!')
